'''
http://projecteuler.net/problem=2
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
Answer: 4613732
'''
#stores the fibanocci of a key as value
fib_map = {}
def fib(n):
    #if already calculated fetch if from map, otherwise calculate
    fib_map[n] = fib_map.get(n, 0) or (n <= 1 and 1 or fib(n-1) + fib(n-2))
    return fib_map[n]

num = 0
i = 0
while fib(i) <= 4000000:
    #check even value
    if not fib(i) % 2:
        num = num + fib(i)
    i = i + 1
print num
